networks:
  rebuilder-network:
    driver: bridge

services:
  training-db:
    image: postgres:13
    environment:
      POSTGRES_DB: training_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - training_data:/var/lib/postgresql/data
    networks:
      - rebuilder-network

  training-service:
    build: ./training-service
    ports:
      - "8001:80"
    environment:
      - DB_HOST=training-db
      - DB_NAME=training_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - training-db
    networks:
      - rebuilder-network
    volumes:
      - ./training-service:/var/www/html

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:80"
    networks:
      - rebuilder-network
    depends_on:
      - training-service

  text-to-speech-service:
    build: ./text-to-speech-service
    ports:
      - "8002:80"
    networks:
      - rebuilder-network
    environment:
      - MURF_API_KEY=ap2_c41bf1a3-3c79-4734-936f-f2c717640d90

volumes:
  training_data: